{
 "title": "mFi mPower & TP-Link HS110",
 "tags": [
  "influxdb",
  "ubiquiti",
  "mfi",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "SmartPlug",
    "label": "Smart Plug",
    "query": "SHOW MEASUREMENTS ON \"telegraf\""
   },
   { "name": "cost", "label": "Cost per kWh", "query": "0.9" }
  ]
 },
 "panels": [
  {
   "title": "Clock",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM tplink\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "ON / OFF status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "$SmartPlug",
     "query": "SELECT \n\"sensors_0_relay\" AS \"Port 1\", \n\"sensors_1_relay\" AS \"Port 2\", \n\"sensors_2_relay\" AS \"Port 3\"\nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "measurement": "$SmartPlug",
     "query": "SELECT \n\"sensors_3_relay\" AS \"Port 4\", \n\"sensors_4_relay\" AS \"Port 5\", \n\"sensors_5_relay\" AS \"Port 6\" \nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       { "params": [ "Port 2" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_power\" AS \"Relay\" FROM /^$SmartPlug$/ WHERE $timeFilter AND  \"emeter_get_realtime_power\" > 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \n\"sensors_0_voltage\" AS \"Port 1\", \n\"sensors_1_voltage\" AS \"Port 2\", \n\"sensors_2_voltage\" AS \"Port 3\"\nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n\"sensors_3_voltage\" AS \"Port 4\", \n\"sensors_4_voltage\" AS \"Port 5\", \n\"sensors_5_voltage\" AS \"Port 6\" \nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_voltage\" AS  \"Voltage\" FROM /^$SmartPlug$/ WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "$SmartPlug",
     "query": "SELECT \n\"sensors_0_power\" AS \"Port 1\", \n\"sensors_1_power\" AS \"Port 2\", \n\"sensors_2_power\" AS \"Port 3\"\nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "measurement": "$SmartPlug",
     "query": "SELECT \n\"sensors_3_power\" AS \"Port 4\", \n\"sensors_4_power\" AS \"Port 5\", \n\"sensors_5_power\" AS \"Port 6\" \nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       { "params": [ "Port 2" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_power\" AS \"Power\" FROM /^$SmartPlug$/ WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \n\"sensors_0_current\" AS \"Port 1\", \n\"sensors_1_current\" AS \"Port 2\", \n\"sensors_2_current\" AS \"Port 3\"\nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \n\"sensors_3_current\" AS \"Port 4\", \n\"sensors_4_current\" AS \"Port 5\", \n\"sensors_5_current\" AS \"Port 6\" \nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_current\" AS \"Current\" FROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_0_power\") AS \"Port 1\", \nmean(\"sensors_1_power\") AS \"Port 2\", \nmean(\"sensors_2_power\") AS \"Port 3\" \nFROM /^$SmartPlug$/  WHERE time > now() - 1h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_3_power\") AS \"Port 4\",\nmean(\"sensors_4_power\") AS \"Port 5\", \nmean(\"sensors_5_power\") AS \"Port 6\" \nFROM /^$SmartPlug$/  WHERE time > now() - 1h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\") as \"Power\" FROM /^$SmartPlug$/  WHERE time > now() - 1h\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_0_power\") AS \"Port 1\", \nmean(\"sensors_1_power\") AS \"Port 2\", \nmean(\"sensors_2_power\") AS \"Port 3\" \nFROM /^$SmartPlug$/  WHERE time > now() - 24h GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_3_power\") AS \"Port 4\",\nmean(\"sensors_4_power\") AS \"Port 5\", \nmean(\"sensors_5_power\") AS \"Port 6\" \nFROM /^$SmartPlug$/ WHERE time > now() - 24h GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\") as \"Power\" FROM /^$SmartPlug$/  WHERE time > now() - 24h GROUP BY time(1h) FILL(0)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Power Factor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \n\"sensors_0_powerfactor\" AS \"Port 1\", \n\"sensors_1_powerfactor\" AS \"Port 2\", \n\"sensors_2_powerfactor\" AS \"Port 3\"\nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \n\"sensors_3_powerfactor\" AS \"Port 4\", \n\"sensors_4_powerfactor\" AS \"Port 5\", \n\"sensors_5_powerfactor\" AS \"Port 6\" \nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (emeter_get_realtime_power / (emeter_get_realtime_voltage * emeter_get_realtime_current) ) AS \"PF\" FROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption 30d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_0_power\") AS \"Port 1\", \nmean(\"sensors_1_power\") AS \"Port 2\", \nmean(\"sensors_2_power\") AS \"Port 3\" \nFROM /^$SmartPlug$/  WHERE time > now() - 30d GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_3_power\") AS \"Port 4\",\nmean(\"sensors_4_power\") AS \"Port 5\", \nmean(\"sensors_5_power\") AS \"Port 6\" \nFROM /^$SmartPlug$/  WHERE time > now() - 30d GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\") as \"Power\" FROM /^$SmartPlug$/  WHERE time > now() - 30d GROUP BY time(1h) FILL(0)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Consumption 1y",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_0_power\") AS \"Port 1\", \nmean(\"sensors_1_power\") AS \"Port 2\", \nmean(\"sensors_2_power\") AS \"Port 3\" \nFROM /^$SmartPlug$/   WHERE time > now() - 365d GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\nmean(\"sensors_3_power\") AS \"Port 4\",\nmean(\"sensors_4_power\") AS \"Port 5\", \nmean(\"sensors_5_power\") AS \"Port 6\" \nFROM /^$SmartPlug$/   WHERE time > now() - 365d GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\") as \"Power\" FROM /^$SmartPlug$/   WHERE time > now() - 365d GROUP BY time(1h) FILL(0)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \n\"sensors_0_power\" AS \"Port 1\", \n\"sensors_1_power\" AS \"Port 2\", \n\"sensors_2_power\" AS \"Port 3\",\n\"sensors_3_power\" AS \"Port 4\",\n\"sensors_4_power\" AS \"Port 5\", \n\"sensors_5_power\" AS \"Port 6\" \nFROM /^$SmartPlug$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\")  AS \"Port\" FROM /^$SmartPlug$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power draw 1h interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Power Draw" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\") as \"Power\" FROM  /^$SmartPlug$/ WHERE $timeFilter GROUP BY time(1h) FILL(0)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"emeter_get_realtime_power\") / 1000 * $cost ) as \"Cost\" FROM  /^$SmartPlug$/ WHERE $timeFilter GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sensors_0_power\") AS \"Power.Port 1\",mean(\"sensors_1_power\") AS \"Power.Port 2\",mean(\"sensors_2_power\") AS \"Power.Port 3\",mean(\"sensors_3_power\") AS \"Power.Port 4\",mean(\"sensors_4_power\") AS \"Power.Port 5\",mean(\"sensors_5_power\") AS \"Power.Port 6\"  FROM  /^$SmartPlug$/ WHERE $timeFilter GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \n(mean(\"sensors_0_power\") / 1000 * $cost ) as \"Cost Port 1\",\n(mean(\"sensors_1_power\") / 1000 * $cost ) as \"Cost Port 2\",\n(mean(\"sensors_2_power\") / 1000 * $cost ) as \"Cost Port 3\",\n(mean(\"sensors_3_power\") / 1000 * $cost ) as \"Cost Port 4\",\n(mean(\"sensors_4_power\") / 1000 * $cost ) as \"Cost Port 5\",\n(mean(\"sensors_5_power\") / 1000 * $cost ) as \"Cost Port 6\"\nFROM  /^$SmartPlug$/ WHERE $timeFilter GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}