{
 "title": "Ubiquiti mFi mPower",
 "description": "Dashboard for Ubiquiti mPower mFi 6-Port and 3-Port Power Switches",
 "tags": [
  "influxdb",
  "ubiquiti",
  "mfi",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "mFi6_PORT1", "query": "PC" },
   { "name": "mFi6_PORT2", "query": "AP34" },
   { "name": "mFi6_PORT3", "query": "DELL" },
   { "name": "mFi6_PORT4", "query": "LIGHT" },
   { "name": "mFi6_PORT5", "query": "PORT5" },
   { "name": "mFi6_PORT6", "query": "OTHER" },
   { "name": "mFi3_PORT1", "query": "Soyuz" },
   { "name": "mFi3_PORT2", "query": "Rover" },
   { "name": "mFi3_PORT3", "query": "Komp" },
   { "name": "kWhPrice", "query": "0.9" },
   {
    "name": "SmartPlug",
    "label": "Smart Plug",
    "query": "SHOW MEASUREMENTS ON \"telegraf\""
   }
  ]
 },
 "panels": [
  {
   "title": "Clock",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM tplink\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "ON / OFF status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_0_relay\" AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_1_relay\" AS \"Port 2\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       { "params": [ "Port 2" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_2_relay\" AS \"Port 3\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       { "params": [ "Port 3" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_3_relay\" AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_4_relay\" AS \"Port 5\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_5_relay\" AS \"Port 6\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_power\" FROM \"$SmartPlug\" WHERE $timeFilter AND  \"emeter_get_realtime_power\" > 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_0_voltage\" AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_1_voltage\" AS \"Port 2\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_2_voltage\" AS \"Port 3\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_3_voltage\" AS \"Port 4\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_4_voltage\" AS \"Port 5\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_5_voltage\" AS \"Port 6\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_voltage\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_0_power\" AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_1_power\" AS \"Port 2\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       { "params": [ "Port 2" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_2_power\" AS \"Port 3\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       { "params": [ "Port 3" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_3_power\" AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_4_power\" AS \"Port 5\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "$SmartPlug",
     "query": "SELECT \"sensors_5_power\" AS \"Port 6\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       { "params": [ "Port 1" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_power\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_0_current\" AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_1_current\" AS \"Port 2\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_2_current\" AS \"Port 3\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_3_current\" AS \"Port 4\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_4_current\" AS \"Port 5\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_5_current\" AS \"Port 6\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"emeter_get_realtime_current\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Power Factor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_0_powerfactor\" AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_1_powerfactor\" AS \"Port 2\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_2_powerfactor\" AS \"Port 3\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_3_powerfactor\" AS \"Port 4\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_4_powerfactor\" AS \"Port 5\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT \"sensors_5_powerfactor\" AS \"Port 6\" FROM \"$SmartPlug\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "sensors_0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT mean(\"sensors_0_power\") AS \"Port 1\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT mean(\"sensors_1_power\") AS \"Port 2\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT mean(\"sensors_2_power\") AS \"Port 3\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT mean(\"sensors_3_power\") AS \"Port 4\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT mean(\"sensors_4_power\") AS \"Port 5\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_mfi6",
     "query": "SELECT mean(\"sensors_5_power\") AS \"Port 6\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sensors_0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT1" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_1_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT2" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_2_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT3" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_3_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT4" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_4_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT5" ], "type": "alias" }
      ],
      [
       { "params": [ "sensors_5_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$mFi6_PORT6" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$SmartPlug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\") FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power draw 1h interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth", "label": "Power Draw" }
   ],
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"emeter_get_realtime_power\") as \"Power\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time(1h) FILL(0)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"emeter_get_realtime_power\") / 1000 * $cost ) as \"apollo_power\" FROM \"$SmartPlug\" WHERE $timeFilter GROUP BY time(1h) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}